package report

import (
	"fmt"
	"io"
	"slices"
	"strings"
	"time"

	"github.com/mhmtkas/fwscan/internal/model"
	"github.com/mhmtkas/fwscan/internal/release"
)

// CRAOptions carries what the evidence report needs beyond the scan results
// themselves: which other artifacts the same run produced, and what the scan
// warned about while it ran.
type CRAOptions struct {
	// SBOMPath is the file --sbom wrote, empty when the flag was not given.
	// Section 3 of the document either names the inventory or says it was not
	// written; it never renders a second copy of it.
	SBOMPath string
	// Warnings are the diagnostics the scan sent to stderr, in the order it
	// sent them. They are the limitations section: a warning that scrolled past
	// in a CI log is not evidence of anything.
	Warnings []string
	// NoNetwork records that the vulnerability lookup was skipped, so the
	// document cannot be read as "nothing was found".
	NoNetwork bool
}

// craDataSource names where the vulnerability data came from, for the
// provenance section. It is the same source the JSON report records.
const craDataSource = "OSV.dev"

// obligationsNotEvidenced are the Annex I Part II obligations no scanner can
// speak to. They are printed in the document itself, every time, because a
// generated file that let a reader assume they were covered would be worse
// than no file at all (output-spec section 5).
var obligationsNotEvidenced = []string{
	"applying regular tests and reviews of the security of the product",
	"publicly disclosing information about fixed vulnerabilities once a fix is available",
	"putting in place and enforcing a coordinated vulnerability disclosure policy",
	"facilitating the sharing of information about potential vulnerabilities with third parties",
	"providing a mechanism to distribute updates securely",
	"disseminating security patches without delay and free of charge",
}

// CRA writes the Markdown evidence report fixed by output-spec section 5.
func CRA(w io.Writer, version string, info ScanInfo, comps []model.Component, findings []model.Finding, opts CRAOptions) error {
	var b strings.Builder
	writeCRAScope(&b)
	writeCRAScan(&b, version, info)
	writeCRAInventory(&b, comps, findings, info, opts)
	writeCRAVulnerabilities(&b, findings, opts)
	writeCRALowConfidence(&b, comps)
	writeCRALimitations(&b, findings, opts)

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("report: write cra: %w", err)
	}
	return nil
}

func writeCRAScope(b *strings.Builder) {
	b.WriteString("# Vulnerability handling evidence\n\n")
	b.WriteString("Generated by fwscan for Annex I, Part II of Regulation (EU) 2024/2847,\n")
	b.WriteString("the Cyber Resilience Act.\n\n")
	b.WriteString("This document records what one scan of one image found. It is not a\n")
	b.WriteString("compliance statement, an audit, or an assessment of a product, and it must\n")
	b.WriteString("not be filed as one. It is evidence toward three of the obligations in that\n")
	b.WriteString("annex — identifying and documenting the components a product contains,\n")
	b.WriteString("establishing which of them carry known vulnerabilities, and recording\n")
	b.WriteString("whether a fix exists — and it is silent on the rest.\n\n")
	b.WriteString("The obligations this document does **not** evidence, because no scanner can\n")
	b.WriteString("observe them from a filesystem:\n\n")
	for _, o := range obligationsNotEvidenced {
		b.WriteString("- " + o + "\n")
	}
	b.WriteString("\nThose are matters of process and require their own records.\n\n")
}

func writeCRAScan(b *strings.Builder, version string, info ScanInfo) {
	b.WriteString("## 1. Scan identification\n\n")
	b.WriteString("| Field | Value |\n|---|---|\n")
	row := func(k, v string) {
		b.WriteString("| " + k + " | " + mdCell(v) + " |\n")
	}
	row("Target", info.Target)
	row("Format", info.Format)
	row("Compression", info.Compression)
	row("Scanned at", info.StartedAt.UTC().Format(time.RFC3339))
	row("Tool", "fwscan "+DisplayVersion(version))
	row("Vulnerability data", craDataSource+", queried "+info.StartedAt.UTC().Format(time.RFC3339))
	b.WriteString("\n")
}

func writeCRAInventory(b *strings.Builder, comps []model.Component, findings []model.Finding, info ScanInfo, opts CRAOptions) {
	counts := CountPackages(comps)
	b.WriteString("## 2. Component inventory\n\n")
	fmt.Fprintf(b, "%d components were identified: %d from a package database, %d from filename heuristics.\n\n",
		counts.Total, counts.HighConfidence, counts.LowConfidence)

	if distros := distributions(comps); len(distros) > 0 {
		b.WriteString("Distributions found in the image: " + mdCell(strings.Join(distros, ", ")) + ".\n\n")
	}
	writeCRASupport(b, comps, findings, info.StartedAt)

	if opts.SBOMPath != "" {
		b.WriteString("The inventory itself is the CycloneDX 1.6 SBOM this run wrote, which is\n" +
			"the machine-readable format the obligation asks for. It is not repeated\n" +
			"here: a second hand-rendered copy would be a second thing to keep true.\n\n")
		b.WriteString("    " + mdCell(opts.SBOMPath) + "\n\n")
		return
	}
	b.WriteString("No SBOM was written by this run. The obligation asks for the inventory in\n" +
		"a commonly used machine-readable format; re-run with `--sbom <file>` to\n" +
		"produce it, and file it alongside this document.\n\n")
}

// writeCRASupport states whether the release still receives security updates.
//
// For this regulation that is the finding, not a footnote. A product shipping a
// release past free support carries vulnerabilities nobody will fix, and every
// one of them is permanent unless the manufacturer backports it. A reader who
// took the vulnerability table at face value without this paragraph would
// conclude the opposite of the truth, because the table is shorter for exactly
// the releases where it should be longer.
func writeCRASupport(b *strings.Builder, comps []model.Component, findings []model.Finding, at time.Time) {
	pkg := distroComponent(comps)
	if pkg == nil {
		return
	}
	support, ok := release.Lookup(pkg.DistroID, pkg.Distro, pkg.DistroVersion, at)
	if !ok {
		b.WriteString("**Support status: unknown.** " + mdCell(pkg.DistroID) +
			" is not a distribution whose release schedule this tool carries, so\n" +
			"whether it still receives security updates has to be established by hand.\n\n")
		return
	}

	name := pkg.DistroID + " " + support.Version
	if support.Series != "" {
		name += " (" + support.Series + ")"
	}
	switch {
	case support.EndOfLife():
		b.WriteString("**Support status: end of life.** " + mdCell(name) + " is past every\n" +
			"support tier its vendor offers. No security updates are published for it by\n" +
			"anyone, and no vulnerability database tracks it, so the section below cannot\n" +
			"be complete and will not become complete. Under this regulation that is\n" +
			"itself the finding.\n\n")
	case !support.FreelySupported():
		fmt.Fprintf(b, "**Support status: paid tier only.** %s left free security support\n"+
			"on %s and is covered until %s by %s. Updates in that tier are not published\n"+
			"to everyone, so a fix named below may require that subscription.\n\n",
			mdCell(name), support.LastFree().Format(time.DateOnly),
			support.Current.Until.Format(time.DateOnly), mdCell(support.Current.Name))
		writeCRARecovered(b, findings)
	default:
		fmt.Fprintf(b, "**Support status: supported.** %s receives free security updates\n"+
			"under %s until %s.\n\n",
			mdCell(name), mdCell(support.Current.Name), support.Current.Until.Format(time.DateOnly))
	}
}

// writeCRARecovered says where the vulnerabilities came from when they did not
// come from the usual place.
//
// A release out of free support is dropped by the database that normally
// answers for it, and the reader has to be told which of two situations they
// are in: the list below was recovered from the vendor's own records, or there
// was nothing to recover it from and the list is short because the data is
// gone. Saying "incomplete" in the first case would tell somebody to distrust a
// report that is not.
func writeCRARecovered(b *strings.Builder, findings []model.Finding) {
	sources := map[string]bool{}
	for _, f := range findings {
		if f.Source != "" {
			sources[f.Source] = true
		}
	}
	if len(sources) == 0 {
		b.WriteString("Vulnerability databases track a release while it is freely supported,\n" +
			"and no fallback source covers this one, so the section below is incomplete.\n\n")
		return
	}
	names := make([]string, 0, len(sources))
	for s := range sources {
		names = append(names, s)
	}
	slices.Sort(names)
	b.WriteString("The vulnerabilities below were read from " + mdCell(strings.Join(names, ", ")) +
		",\nthe vendor's own records, because the database that normally answers for this\n" +
		"release stopped carrying it when free support ended.\n\n")
}

// distroComponent picks the component the release is read from: any one that
// came from a package database and named a distribution. They all name the same
// one, because they all came from the same image.
func distroComponent(comps []model.Component) *model.Component {
	for i := range comps {
		if comps[i].DistroID != "" && comps[i].Confidence == model.ConfidenceHigh {
			return &comps[i]
		}
	}
	return nil
}

func writeCRAVulnerabilities(b *strings.Builder, findings []model.Finding, opts CRAOptions) {
	b.WriteString("## 3. Known vulnerabilities\n\n")
	if opts.NoNetwork {
		b.WriteString("The scan ran with `--no-network`, so no vulnerability lookup was performed.\n" +
			"This section is empty because nothing was checked, not because nothing was\n" +
			"found.\n\n")
		return
	}
	if len(findings) == 0 {
		b.WriteString("No known vulnerabilities were reported for the components identified above.\n" +
			"Read that together with section 5: it is a statement about what the data\n" +
			"source holds for these packages, not a statement that the image is sound.\n\n")
		return
	}

	sorted := slices.Clone(findings)
	slices.SortFunc(sorted, model.CompareFindings)

	fixable := 0
	for _, f := range sorted {
		if f.FixedVersion != "" {
			fixable++
		}
	}
	fmt.Fprintf(b, "%d findings. %d have a fix published for the installed release; %d do not.\n\n",
		len(sorted), fixable, len(sorted)-fixable)

	counts := CountFindings(sorted)
	b.WriteString("| Severity | Count |\n|---|---|\n")
	for _, row := range []struct {
		name string
		n    int
	}{
		{"critical", counts.Critical},
		{"high", counts.High},
		{"medium", counts.Medium},
		{"low", counts.Low},
		{"unknown", counts.Unknown},
	} {
		fmt.Fprintf(b, "| %s | %d |\n", row.name, row.n)
	}
	b.WriteString("\n")

	b.WriteString("The `Justification` column is deliberately empty. An unresolved finding\n" +
		"needs a reason recorded against it, and that reason belongs to whoever ships\n" +
		"the product, not to the tool that found it.\n\n")

	b.WriteString("| Vulnerability | Component | Installed | Severity | Status | Justification |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, f := range sorted {
		status := "no fix published"
		if f.FixedVersion != "" {
			status = "fix available: " + f.FixedVersion
		}
		b.WriteString("| " + mdCell(f.ID) +
			" | " + mdCell(f.Component.Name) +
			" | " + mdCell(f.Component.Version) +
			" | " + mdCell(string(f.Severity)) +
			" | " + mdCell(status) +
			" |  |\n")
	}
	b.WriteString("\n")
}

func writeCRALowConfidence(b *strings.Builder, comps []model.Component) {
	var low []model.Component
	for _, c := range comps {
		if c.Confidence != model.ConfidenceHigh {
			low = append(low, c)
		}
	}
	if len(low) == 0 {
		return
	}
	slices.SortFunc(low, model.CompareComponents)

	b.WriteString("## 4. Components identified without a package database\n\n")
	b.WriteString("These were recognised from a filename or an embedded version string. They\n" +
		"were **not** checked for vulnerabilities: a version read from a filename\n" +
		"carries no release to scope a query to, and an unscoped query invents\n" +
		"vulnerabilities rather than finding them. Each needs confirming by hand\n" +
		"before it is treated as inventory.\n\n")
	b.WriteString("| Component | Version | Evidence |\n|---|---|---|\n")
	for _, c := range low {
		b.WriteString("| " + mdCell(c.Name) + " | " + mdCell(c.Version) + " | `" + mdCell(c.Evidence) + "` |\n")
	}
	b.WriteString("\n")
}

func writeCRALimitations(b *strings.Builder, findings []model.Finding, opts CRAOptions) {
	b.WriteString("## 5. Limitations of this scan\n\n")

	items := slices.Clone(opts.Warnings)
	if n := CountFindings(findings).Unknown; n > 0 {
		carry, appear := "findings carry", "They appear in the table above as `unknown` and are not ranked"
		if n == 1 {
			carry, appear = "finding carries", "It appears in the table above as `unknown` and is not ranked"
		}
		items = append(items, fmt.Sprintf(
			"%d %s no severity score, because the record it came from published no "+
				"CVSS vector. %s.", n, carry, appear))
	}
	items = append(items,
		"Binaries not accounted for by a package database are not fingerprinted. "+
			"A statically linked library compiled into an executable is invisible to "+
			"this scan.",
		"Findings reflect what "+craDataSource+" held at the time in section 1. "+
			"A vulnerability published after that is not in this document.")

	for _, item := range items {
		b.WriteString("- " + mdCell(item) + "\n")
	}
	b.WriteString("\n")
}

// distributions lists the distributions the components came from, so section 2
// says which bodies of vulnerability data this scan actually reached.
func distributions(comps []model.Component) []string {
	var names []string
	for _, c := range comps {
		name := c.DistroID
		if name == "" {
			continue
		}
		if c.Distro != "" {
			name += " " + c.Distro
		}
		if !slices.Contains(names, name) {
			names = append(names, name)
		}
	}
	slices.Sort(names)
	return names
}

// mdCell makes a string from the image safe to place in the document.
//
// Sanitize comes first and does most of it: it replaces every control
// character, so a newline in a crafted package name cannot end a table row and
// forge the next one. What it does not cover is Markdown's own structure. A
// pipe is an ordinary printable character and ends a cell, shifting every
// column after it, which turns a package name into a fabricated severity in a
// document somebody files. The backslash is escaped first, or a payload
// containing a literal \| would come out as an escaped pipe rather than as the
// two characters it really is.
func mdCell(s string) string {
	s = Sanitize(s)
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "|", "\\|")
	return s
}
